sudo: false
language: java
jdk: openjdk8
dist: trusty
addons:
  apt:
    packages:
    - rpm
before_install:
- mvn initialize
before_deploy:
- mvn jdeb:jdeb && export RELEASE_DEB_FILE=$(ls target/*.deb)
- mvn rpm:rpm && export RELEASE_RPM_FILE=$(find target/ -name '*.rpm' | tail -1)
- rm -f target/original-*.jar
- export RELEASE_PKG_FILE=$(ls target/*.jar)
- echo "Deploying release to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: BRWRiAXDDuX/KH6PMFf+ADVR7ACPKHSXALvV8ZXZytpX5aQ78yl+5D12GrXR+FRyYlmQhRckhFyRAT2lWYQOXEt+yCZpgEvl0DxV0X1mk5wyaVQIcoS5A96MMPmD7d3IWarorJy7DQ3ZD0Wkhdrwb1aoh7AIPUADaA+thuFtLTNFkBkr/DuRQTO/FFkq38E3s13dMJeQTTyp0fWBmVIAlpcwo/EgrkCtdxtBZ8jphVmc7tJY92tKMqhBrp0kRAOe4ZGTqk8xt+UWhBjzh8FQK6ZGFBUhVCIozYZIYATbakcMNjh2m0rpdwfbgVuKMh8ze55dt5iqejp8uZqYVlABecuCS3k/tnZEBwrxNYnXsB1XXs1BG1wD3MoWgB/yEKgm5/zxAp825x9uGKKPCrPbw/CXR/2PpQuQjmX5gyERnTcWohXbMDVH/NjVOw+qCvB2qEcn8he69noYO/9ZQBt6lMd9RHfDrFwOA/7Qtd2UFkCJ8DvH9+VkD6Ik6g6t+w4ucf40nBFDc4a4qZvyb1ZdASVG7g7aMhaml1NG7DZ1ckCd6CrXpZ8//M1yJqUjoKVDmDXQmWU7IuOA6ElIhKbUw2TGSTkuDJurVw17CSR+V30UTuWdIVVZfflYNCMqoDiPbcDeuE9RiI/fPXi954DHOVZMRSVi+fl6+BG/zPjRyRk=
  file:
  - "${RELEASE_PKG_FILE}"
  - "${RELEASE_DEB_FILE}"
  - "${RELEASE_RPM_FILE}"
  on:
    repo: cvtienhoven/graylog-plugin-topdesk
    tags: true
    jdk: openjdk8
  skip_cleanup: 'true'
